// Build-time generator for the explore-landing US map. Emits a COMMITTED module
// (src/lib/usMap.js) so the app needs no runtime map deps and no fetch.
//
// us-atlas `states-10m` ships GEOGRAPHIC (lon/lat) coordinates, so we project
// both the state outlines and each city's [lat, lon] with ONE shared
// d3.geoAlbersUsa().scale(1300).translate([487.5, 305]) (the 975x610 standard).
// We keep only the states that fall in view (the interior West) and crop the
// viewBox to the cities' bounding box so the SW cluster reads at a useful zoom.
//
// Re-run after adding/moving a city:
//   cd apps/web && npm i --no-save us-atlas@3 topojson-client@3 d3-geo@3 \
//     && node scripts/build-map.mjs
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { feature } from "topojson-client";
import { geoAlbersUsa, geoPath, geoContains } from "d3-geo";
import { CITIES } from "../src/lib/cities.js";

const require = createRequire(import.meta.url);
const topo = require("us-atlas/states-10m.json");

const projection = geoAlbersUsa().scale(1300).translate([487.5, 305]);
const path = geoPath(projection);

const fips2 = {
  AZ: "04", CA: "06", CO: "08", ID: "16", NM: "35", NV: "32",
  OR: "41", TX: "48", UT: "49", WA: "53", WY: "56", MT: "30",
};
const stateOf = (city) => {
  const m = /,\s*([A-Z]{2})\b/.exec(city.name);
  if (!m || !fips2[m[1]]) throw new Error(`No FIPS for city ${city.id} (${city.name})`);
  return fips2[m[1]];
};

const states = feature(topo, topo.objects.states).features;
// geoAlbersUsa draws AK/HI as insets that would float into a SW window, and
// territories sit off-continent; drop them so this stays a contiguous-US view.
const SKIP_FIPS = new Set(["02", "15", "60", "66", "69", "72", "78"]);
const byFips = new Map(states.map((s) => [String(s.id), s]));

// Project cities and validate each falls inside its expected state polygon
// (spherical geoContains, on the raw lon/lat geometry).
const cities = {};
for (const c of CITIES) {
  if (!Array.isArray(c.latLon)) throw new Error(`city ${c.id} has no latLon`);
  const [lat, lon] = c.latLon;
  const st = byFips.get(stateOf(c));
  if (!st) throw new Error(`state feature ${stateOf(c)} not in atlas for ${c.id}`);
  if (!geoContains(st, [lon, lat])) {
    throw new Error(`PROJECTION CHECK FAILED: ${c.id} ${JSON.stringify(c.latLon)} ` +
      `not inside ${st.properties.name}`);
  }
  const xy = projection([lon, lat]);
  if (!xy) throw new Error(`city ${c.id} projected to null (outside geoAlbersUsa)`);
  cities[c.id] = [Math.round(xy[0] * 10) / 10, Math.round(xy[1] * 10) / 10];
}

// Crop the viewBox to the cities' bbox + margin, clamped to the atlas extent.
const xs = Object.values(cities).map((p) => p[0]);
const ys = Object.values(cities).map((p) => p[1]);
const x0 = Math.min(...xs), x1 = Math.max(...xs);
const y0 = Math.min(...ys), y1 = Math.max(...ys);
const padX = Math.max((x1 - x0) * 0.28, 70);
const padY = Math.max((y1 - y0) * 0.28, 70);
const vbX = Math.max(0, x0 - padX);
const vbY = Math.max(0, y0 - padY);
const vbW = Math.min(975, x1 + padX) - vbX;
const vbH = Math.min(610, y1 + padY) - vbY;
const view = { x: vbX, y: vbY, w: vbW, h: vbH };

const intersects = (b) => b &&
  b[1][0] >= view.x && b[0][0] <= view.x + view.w &&
  b[1][1] >= view.y && b[0][1] <= view.y + view.h;

// Keep only states visible in the cropped window; round path coords to 1dp.
const round1 = (d) => d.replace(/-?\d+\.\d+/g, (n) => (Math.round(+n * 10) / 10).toString());
const keptStates = [];
for (const s of states) {
  if (SKIP_FIPS.has(String(s.id))) continue;
  const b = path.bounds(s);
  if (!Number.isFinite(b[0][0]) || !intersects(b)) continue;
  const d = round1(path(s));
  if (d) keptStates.push({ id: String(s.id), name: s.properties.name, d });
}

const r = (n) => Math.round(n * 10) / 10;
const out =
`// AUTO-GENERATED by scripts/build-map.mjs — do not edit by hand.
// Interior-West states + each city's projected [x, y], shared d3 geoAlbersUsa
// (us-atlas states-10m). Re-run scripts/build-map.mjs after adding/moving a city.
export const US_MAP = {
  viewBox: "${r(view.x)} ${r(view.y)} ${r(view.w)} ${r(view.h)}",
  states: ${JSON.stringify(keptStates)},
  cities: ${JSON.stringify(cities)},
};
`;
const dest = fileURLToPath(new URL("../src/lib/usMap.js", import.meta.url));
writeFileSync(dest, out);
console.log(`wrote ${dest}`);
console.log(`  viewBox ${out.match(/viewBox: "([^"]+)"/)[1]}`);
console.log(`  states kept: ${keptStates.map((s) => s.name).join(", ")}`);
console.log(`  cities: ${Object.entries(cities).map(([k, v]) => `${k}[${v}]`).join(" ")}`);
