// Tucson — the second desert-UHI city. Same engine, different station + rural
// pair. City station validated against ACIS (TUSthr 9 = "Tucson Area", record
// from 1894); overnight lows have risen ~4°F since the 1970s (NCEI GSOY, airport
// USW00023160). Precomputed assets (tus-*.json) are generated by the "Rebuild
// data assets" workflow; until it runs, the live-ACIS cards render and the
// asset-backed cards stay hidden.
export const TUCSON = {
  id: "tus",
  name: "Tucson, AZ",
  shortName: "Tucson",
  threadSid: "TUSthr 9",
  recordStart: "1895-01-01",
  stationLabel:
    "Tucson Area ThreadEx record (University/downtown early record spliced to Tucson Int'l Airport, KTUS)",
  urbanShort: "Tucson Int'l",
  baseline: { start: 1970, end: 1979, label: "1970s" },
  windows: [
    { y: 1970, label: "Since 1970" },
    { y: 1948, label: "Since 1948" },
  ],
  latLon: [32.1313, -110.9553],
  rural: {
    sid: "USC00027619",
    name: "Sasabe",
    short: "Sasabe",
    firstYear: 1960,
    distance: "~55 miles southwest",
    elevationNote:
      "Sasabe sits ~1,040 ft higher than Tucson Int'l, so much of the absolute gap is elevation — the honest signal is the gap's growth, not its size.",
    growthCaveat:
      "the Altar Valley around Sasabe is sparsely developed, so the desert reference stays comparatively rural; if anything that makes the city's excess warming a conservative read.",
    robustnessNote:
      "Sasabe's COOP record has multi-year gaps; the city-vs-desert gap and its growth are computed from the complete years and re-checked from ACIS in verify_v0.py. It is the longest continuous desert reference near Tucson — nearer COOP sites (e.g. Anvil Ranch) are too gappy to anchor a 1970s baseline.",
  },
  citations: [
    {
      label: "NOAA/NWS ACIS web services",
      url: "https://www.rcc-acis.org/docs_webservices.html",
      note: "The official station record this page queries live in your browser.",
    },
    {
      label: "NWS Tucson (Weather Forecast Office) — local climate records",
      url: "https://www.weather.gov/twc/",
      note: "Local climate normals and records for the Tucson area.",
    },
    {
      label: "University of Arizona AZMet — Arizona Meteorological Network",
      url: "https://azmet.arizona.edu/",
      note: "Regional Arizona climate and station monitoring.",
    },
    {
      label: "Comrie, \"Mapping a Wind-Modified Urban Heat Island in Tucson, Arizona\" (Bull. Amer. Meteor. Soc., 2000)",
      url: "https://doi.org/10.1175/1520-0477(2000)081%3C2417:MAWMUH%3E2.3.CO;2",
      note: "Documents Tucson's measurable nighttime urban heat island.",
    },
  ],
  repoUrl: "https://github.com/poetac/phoenix_nights",
  // heatDeathsAsset intentionally omitted — see analysis/HEAT_DEATHS.md
  // "Second city (Tucson / Pima County)". The only primary year-by-year
  // heat-related (caused+contributed) series for Pima (AZDHS) is ~half
  // undocumented border-crossing deaths in the remote desert — a different
  // phenomenon from the urban heat-mortality this card shows — plus a 2023
  // surveillance-method break, and Pima publishes no demographic breakdown
  // comparable to Maricopa's. The fetcher returns null when this is absent,
  // so the card simply omits for Tucson (reproduce-or-reject => reject).
  // decennial census, Pima County (US Census Bureau)
  county: "Pima County",
  metroPopulation: {
    1950: 141216, 1960: 265660, 1970: 351667, 1980: 531443,
    1990: 666880, 2000: 843746, 2010: 980263, 2020: 1043433,
  },
};
