// Per-city configuration — everything the dashboard and fetchers need to
// render one city. Adding a city means adding an entry here (plus optional
// precomputed assets under public/data/), not touching the components.
export const PHOENIX = {
  id: "phx",
  name: "Phoenix, AZ",
  shortName: "Phoenix",
  threadSid: "PHXthr 9",
  recordStart: "1896-01-01",
  stationLabel:
    "Phoenix ThreadEx station record (downtown 1896–1933, Sky Harbor 1933–present)",
  urbanShort: "Sky Harbor",
  baseline: { start: 1970, end: 1979, label: "1970s" },
  // window choices offered in the UI; the full record is appended dynamically
  windows: [
    { y: 1970, label: "Since 1970" },
    { y: 1948, label: "Since 1948" },
  ],
  latLon: [33.4278, -112.0037],
  rural: {
    sid: "USC00021314",
    name: "Casa Grande National Monument",
    short: "Casa Grande NM",
    firstYear: 1948,
    distance: "~45 miles",
    elevationNote:
      "The monument station sits ~300 ft higher than Sky Harbor, so part of the absolute gap is elevation — the honest signal is the gap's growth, not its size.",
    growthCaveat:
      "the Casa Grande–Maricopa corridor has been booming, so the \"rural\" reference is slowly growing its own heat island. If anything, that makes the city share above an underestimate.",
    robustnessNote:
      "Robustness: swapping the desert reference for Wickenburg (record through 2014) or Sacaton (through 2011) raises the city share to 62–67% — this card shows the most conservative of the three. Reproduce with analysis/uhi_robustness.py.",
  },
  citations: [
    {
      label: "Brazel et al., \"The tale of two climates — Baseline and urban heat island analyses of the Phoenix region\"",
      url: "https://www.researchgate.net/publication/226592731",
      note: "Urbanization raised Sky Harbor nighttime minimums ~9°F — far more than daily averages.",
    },
    {
      label: "Climate Central via NPR (2023): Phoenix summer nights warmed ~6°F since 1970",
      url: "https://www.npr.org/2023/07/14/1187646149/",
      note: "The seasonal card reproduces this figure from the raw station record.",
    },
    {
      label: "ASU Arizona Climate: the Phoenix urban heat island",
      url: "https://globalfutures.asu.edu/azclimate/urban-heat-island/",
      note: "Documents the 10–14°F urban-rural temperature gap this page measures live.",
    },
    {
      label: "Maricopa County heat surveillance reports",
      url: "https://www.maricopa.gov/1858/Heat-Surveillance",
      note: "Source of the confirmed heat-death counts in the human-cost card.",
    },
    {
      label: "NOAA/NWS ACIS web services",
      url: "https://www.rcc-acis.org/docs_webservices.html",
      note: "The official station record this page queries live in your browser.",
    },
    {
      label: "US EIA Hourly Electric Grid Monitor",
      url: "https://www.eia.gov/electricity/gridmonitor/",
      note: "Source of the hourly demand curves in the grid card.",
    },
  ],
  repoUrl: "https://github.com/poetac/phoenix_nights",
  // built by analysis/build_diurnal.py from NCEI hourly observations
  diurnalAsset: "data/phx-diurnal.json",
  // built by analysis/build_heat_season.py from ACIS daily highs
  heatSeasonAsset: "data/phx-heat-season.json",
  // hand-verified from the county's annual report (see the JSON's source field)
  heatDeathsAsset: "data/phx-heat-deaths.json",
  // built by analysis/build_streaks.py from ACIS daily lows/highs
  streaksAsset: "data/phx-streaks.json",
  // built by analysis/build_grid.py from EIA-930 hourly demand (needs EIA_API_KEY)
  gridAsset: "data/phx-grid.json",
  // built by analysis/build_normals.py from ACIS 1970s daily lows/highs (hero baseline)
  normalsAsset: "data/phx-normals.json",
  // built by analysis/build_cdd_split.py — annual CDD split into day/night halves
  cddSplitAsset: "data/phx-cdd-split.json",
  // decennial census, Maricopa County (US Census Bureau)
  metroPopulation: {
    1950: 331770, 1960: 663510, 1970: 971228, 1980: 1509175,
    1990: 2122101, 2000: 3072149, 2010: 3817117, 2020: 4420568,
  },
};

// Tucson — the second desert-UHI city. Same engine, different station + rural
// pair. City station validated against ACIS (TUSthr 9 = "Tucson Area", record
// from 1894); overnight lows have risen ~4°F since the 1970s (NCEI GSOY, airport
// USW00023160). Precomputed assets (tus-*.json) are generated by the "Rebuild
// data assets" workflow; until it runs, the live-ACIS cards render and the
// asset-backed cards stay hidden.
export const TUCSON = {
  id: "tus",
  name: "Tucson, AZ",
  shortName: "Tucson",
  threadSid: "TUSthr 9",
  recordStart: "1895-01-01",
  stationLabel:
    "Tucson Area ThreadEx record (University/downtown early record spliced to Tucson Int'l Airport, KTUS)",
  urbanShort: "Tucson Int'l",
  baseline: { start: 1970, end: 1979, label: "1970s" },
  windows: [
    { y: 1970, label: "Since 1970" },
    { y: 1948, label: "Since 1948" },
  ],
  latLon: [32.1313, -110.9553],
  rural: {
    sid: "USC00027619",
    name: "Sasabe",
    short: "Sasabe",
    firstYear: 1960,
    distance: "~55 miles southwest",
    elevationNote:
      "Sasabe sits ~1,040 ft higher than Tucson Int'l, so much of the absolute gap is elevation — the honest signal is the gap's growth, not its size.",
    growthCaveat:
      "the Altar Valley around Sasabe is sparsely developed, so the desert reference stays comparatively rural; if anything that makes the city's excess warming a conservative read.",
    robustnessNote:
      "Sasabe's COOP record has multi-year gaps; the city-vs-desert gap and its growth are computed from the complete years and re-checked from ACIS in verify_v0.py. It is the longest continuous desert reference near Tucson — nearer COOP sites (e.g. Anvil Ranch) are too gappy to anchor a 1970s baseline.",
  },
  citations: [
    {
      label: "NOAA/NWS ACIS web services",
      url: "https://www.rcc-acis.org/docs_webservices.html",
      note: "The official station record this page queries live in your browser.",
    },
    {
      label: "NWS Tucson (Weather Forecast Office) — local climate records",
      url: "https://www.weather.gov/twc/",
      note: "Local climate normals and records for the Tucson area.",
    },
    {
      label: "University of Arizona AZMet — Arizona Meteorological Network",
      url: "https://azmet.arizona.edu/",
      note: "Regional Arizona climate and station monitoring.",
    },
    {
      label: "Comrie, \"Mapping a Wind-Modified Urban Heat Island in Tucson, Arizona\" (Bull. Amer. Meteor. Soc., 2000)",
      url: "https://doi.org/10.1175/1520-0477(2000)081%3C2417:MAWMUH%3E2.3.CO;2",
      note: "Documents Tucson's measurable nighttime urban heat island.",
    },
  ],
  repoUrl: "https://github.com/poetac/phoenix_nights",
  diurnalAsset: "data/tus-diurnal.json",
  heatSeasonAsset: "data/tus-heat-season.json",
  // heatDeathsAsset intentionally omitted — see analysis/HEAT_DEATHS.md
  // "Second city (Tucson / Pima County)". The only primary year-by-year
  // heat-related (caused+contributed) series for Pima (AZDHS) is ~half
  // undocumented border-crossing deaths in the remote desert — a different
  // phenomenon from the urban heat-mortality this card shows — plus a 2023
  // surveillance-method break, and Pima publishes no demographic breakdown
  // comparable to Maricopa's. The fetcher returns null when this is absent,
  // so the card simply omits for Tucson (reproduce-or-reject => reject).
  streaksAsset: "data/tus-streaks.json",
  gridAsset: "data/tus-grid.json",
  normalsAsset: "data/tus-normals.json",
  cddSplitAsset: "data/tus-cdd-split.json",
  // decennial census, Pima County (US Census Bureau)
  metroPopulation: {
    1950: 141216, 1960: 265660, 1970: 351667, 1980: 531443,
    1990: 666880, 2000: 843746, 2010: 980263, 2020: 1043433,
  },
};

// The city registry the picker iterates. Phoenix is the flagship (first).
export const CITIES = [PHOENIX, TUCSON];
