// Per-city configuration — everything the dashboard and fetchers need to
// render one city. Adding a city means adding an entry here (plus optional
// precomputed assets under public/data/), not touching the components.
export const PHOENIX = {
  id: "phx",
  name: "Phoenix, AZ",
  shortName: "Phoenix",
  threadSid: "PHXthr 9",
  recordStart: "1896-01-01",
  stationLabel:
    "Phoenix ThreadEx station record (downtown 1896–1933, Sky Harbor 1933–present)",
  urbanShort: "Sky Harbor",
  // Curated flagship overlay: Phoenix keeps its hand-written hero; other cities
  // get an auto hero built from their top-ranked fact (see CityDashboard).
  featured: {
    line1: "The desert still cools off at night.",
    line2: "The city doesn\u2019t.",
    sub: "Weather apps grade each day against a \"normal range\" and spotlight the afternoon high. This page tests a different question with the official record: are Phoenix\u2019s overnight lows abandoning their history faster than its highs?",
  },
  baseline: { start: 1970, end: 1979, label: "1970s" },
  // window choices offered in the UI; the full record is appended dynamically
  windows: [
    { y: 1970, label: "Since 1970" },
    { y: 1948, label: "Since 1948" },
  ],
  latLon: [33.4278, -112.0037],
  rural: {
    sid: "USC00021314",
    name: "Casa Grande National Monument",
    short: "Casa Grande NM",
    firstYear: 1948,
    distance: "~45 miles",
    elevationNote:
      "The monument station sits ~300 ft higher than Sky Harbor, so part of the absolute gap is elevation — the honest signal is the gap's growth, not its size.",
    growthCaveat:
      "the Casa Grande–Maricopa corridor has been booming, so the \"rural\" reference is slowly growing its own heat island. If anything, that makes the city share above an underestimate.",
    robustnessNote:
      "Robustness: swapping the desert reference for Wickenburg (record through 2014) or Sacaton (through 2011) raises the city share to 62–67% — this card shows the most conservative of the three. Reproduce with analysis/uhi_robustness.py.",
  },
  citations: [
    {
      label: "Brazel et al., \"The tale of two climates — Baseline and urban heat island analyses of the Phoenix region\"",
      url: "https://www.researchgate.net/publication/226592731",
      note: "Urbanization raised Sky Harbor nighttime minimums ~9°F — far more than daily averages.",
    },
    {
      label: "Climate Central via NPR (2023): Phoenix summer nights warmed ~6°F since 1970",
      url: "https://www.npr.org/2023/07/14/1187646149/",
      note: "The seasonal card reproduces this figure from the raw station record.",
    },
    {
      label: "ASU Arizona Climate: the Phoenix urban heat island",
      url: "https://globalfutures.asu.edu/azclimate/urban-heat-island/",
      note: "Documents the 10–14°F urban-rural temperature gap this page measures live.",
    },
    {
      label: "Maricopa County heat surveillance reports",
      url: "https://www.maricopa.gov/1858/Heat-Surveillance",
      note: "Source of the confirmed heat-death counts in the human-cost card.",
    },
    {
      label: "NOAA/NWS ACIS web services",
      url: "https://www.rcc-acis.org/docs_webservices.html",
      note: "The official station record this page queries live in your browser.",
    },
    {
      label: "US EIA Hourly Electric Grid Monitor",
      url: "https://www.eia.gov/electricity/gridmonitor/",
      note: "Source of the hourly demand curves in the grid card.",
    },
  ],
  repoUrl: "https://github.com/poetac/phoenix_nights",
  // built by analysis/build_diurnal.py from NCEI hourly observations
  diurnalAsset: "data/phx-diurnal.json",
  // built by analysis/build_heat_season.py from ACIS daily highs
  heatSeasonAsset: "data/phx-heat-season.json",
  // hand-verified from the county's annual report (see the JSON's source field)
  heatDeathsAsset: "data/phx-heat-deaths.json",
  // built by analysis/build_streaks.py from ACIS daily lows/highs
  streaksAsset: "data/phx-streaks.json",
  // built by analysis/build_grid.py from EIA-930 hourly demand (needs EIA_API_KEY)
  gridAsset: "data/phx-grid.json",
  // built by analysis/build_normals.py from ACIS 1970s daily lows/highs (hero baseline)
  normalsAsset: "data/phx-normals.json",
  // built by analysis/build_cdd_split.py — annual CDD split into day/night halves
  cddSplitAsset: "data/phx-cdd-split.json",
  // decennial census, Maricopa County (US Census Bureau)
  metroPopulation: {
    1950: 331770, 1960: 663510, 1970: 971228, 1980: 1509175,
    1990: 2122101, 2000: 3072149, 2010: 3817117, 2020: 4420568,
  },
};

// Tucson — the second desert-UHI city. Same engine, different station + rural
// pair. City station validated against ACIS (TUSthr 9 = "Tucson Area", record
// from 1894); overnight lows have risen ~4°F since the 1970s (NCEI GSOY, airport
// USW00023160). Precomputed assets (tus-*.json) are generated by the "Rebuild
// data assets" workflow; until it runs, the live-ACIS cards render and the
// asset-backed cards stay hidden.
export const TUCSON = {
  id: "tus",
  name: "Tucson, AZ",
  shortName: "Tucson",
  threadSid: "TUSthr 9",
  recordStart: "1895-01-01",
  stationLabel:
    "Tucson Area ThreadEx record (University/downtown early record spliced to Tucson Int'l Airport, KTUS)",
  urbanShort: "Tucson Int'l",
  baseline: { start: 1970, end: 1979, label: "1970s" },
  windows: [
    { y: 1970, label: "Since 1970" },
    { y: 1948, label: "Since 1948" },
  ],
  latLon: [32.1313, -110.9553],
  rural: {
    sid: "USC00027619",
    name: "Sasabe",
    short: "Sasabe",
    firstYear: 1960,
    distance: "~55 miles southwest",
    elevationNote:
      "Sasabe sits ~1,040 ft higher than Tucson Int'l, so much of the absolute gap is elevation — the honest signal is the gap's growth, not its size.",
    growthCaveat:
      "the Altar Valley around Sasabe is sparsely developed, so the desert reference stays comparatively rural; if anything that makes the city's excess warming a conservative read.",
    robustnessNote:
      "Sasabe's COOP record has multi-year gaps; the city-vs-desert gap and its growth are computed from the complete years and re-checked from ACIS in verify_v0.py. It is the longest continuous desert reference near Tucson — nearer COOP sites (e.g. Anvil Ranch) are too gappy to anchor a 1970s baseline.",
  },
  citations: [
    {
      label: "NOAA/NWS ACIS web services",
      url: "https://www.rcc-acis.org/docs_webservices.html",
      note: "The official station record this page queries live in your browser.",
    },
    {
      label: "NWS Tucson (Weather Forecast Office) — local climate records",
      url: "https://www.weather.gov/twc/",
      note: "Local climate normals and records for the Tucson area.",
    },
    {
      label: "University of Arizona AZMet — Arizona Meteorological Network",
      url: "https://azmet.arizona.edu/",
      note: "Regional Arizona climate and station monitoring.",
    },
    {
      label: "Comrie, \"Mapping a Wind-Modified Urban Heat Island in Tucson, Arizona\" (Bull. Amer. Meteor. Soc., 2000)",
      url: "https://doi.org/10.1175/1520-0477(2000)081%3C2417:MAWMUH%3E2.3.CO;2",
      note: "Documents Tucson's measurable nighttime urban heat island.",
    },
  ],
  repoUrl: "https://github.com/poetac/phoenix_nights",
  diurnalAsset: "data/tus-diurnal.json",
  heatSeasonAsset: "data/tus-heat-season.json",
  // heatDeathsAsset intentionally omitted — see analysis/HEAT_DEATHS.md
  // "Second city (Tucson / Pima County)". The only primary year-by-year
  // heat-related (caused+contributed) series for Pima (AZDHS) is ~half
  // undocumented border-crossing deaths in the remote desert — a different
  // phenomenon from the urban heat-mortality this card shows — plus a 2023
  // surveillance-method break, and Pima publishes no demographic breakdown
  // comparable to Maricopa's. The fetcher returns null when this is absent,
  // so the card simply omits for Tucson (reproduce-or-reject => reject).
  streaksAsset: "data/tus-streaks.json",
  gridAsset: "data/tus-grid.json",
  normalsAsset: "data/tus-normals.json",
  cddSplitAsset: "data/tus-cdd-split.json",
  // decennial census, Pima County (US Census Bureau)
  metroPopulation: {
    1950: 141216, 1960: 265660, 1970: 351667, 1980: 531443,
    1990: 666880, 2000: 843746, 2010: 980263, 2020: 1043433,
  },
};


// Third city. Las Vegas observes Pacific DST, so its hour-of-day assets are
// bucketed via the IANA tz in analysis/cities.py (the AZ cities use a fixed
// offset). McCarran/Harry Reid is the fastest-warming of the three at night.
export const LASVEGAS = {
  id: "lv",
  name: "Las Vegas, NV",
  shortName: "Las Vegas",
  threadSid: "LASthr 9",
  recordStart: "1937-01-01",
  stationLabel:
    "Las Vegas Area ThreadEx record (early downtown record spliced to Harry Reid Intl, KLAS)",
  urbanShort: "Harry Reid",
  baseline: { start: 1970, end: 1979, label: "1970s" },
  windows: [
    { y: 1970, label: "Since 1970" },
    { y: 1948, label: "Since 1948" },
  ],
  latLon: [36.084, -115.1537],
  rural: {
    sid: "USC00262243",
    name: "Desert National Wildlife Refuge",
    short: "Desert NWR",
    firstYear: 1948,
    distance: "~25 miles north",
    elevationNote:
      "Desert NWR sits ~740 ft higher than Harry Reid Intl, so part of the absolute gap is elevation — the honest signal is the gap's growth, not its size.",
    growthCaveat:
      "the Desert National Wildlife Refuge is protected open desert, so the reference stays genuinely rural — if anything that makes the city's excess warming a conservative read.",
    robustnessNote:
      "The refuge COOP record has multi-year gaps; the city-vs-desert gap and its growth are computed from the complete years and re-checked from ACIS in verify_v0.py.",
  },
  citations: [
    {
      label: "NOAA/NWS ACIS web services",
      url: "https://www.rcc-acis.org/docs_webservices.html",
      note: "The official station record this page queries live in your browser.",
    },
    {
      label: "NWS Las Vegas (Weather Forecast Office, VEF) — local climate records",
      url: "https://www.weather.gov/vef/",
      note: "Local climate normals and records for the Las Vegas / Harry Reid area.",
    },
    {
      label: "Western Regional Climate Center (DRI) — Nevada climate data",
      url: "https://wrcc.dri.edu/",
      note: "Regional station records and summaries for Nevada and the Southwest.",
    },
    {
      label: "Climate Central, \"Warm Summer Nights\" (2025)",
      url: "https://www.climatecentral.org/climate-matters/warm-summer-nights-2025",
      note: "Las Vegas summer nights have warmed ~10°F since 1970 — the 2nd-largest of 241 U.S. locations analyzed (after Reno).",
    },
  ],
  repoUrl: "https://github.com/poetac/phoenix_nights",
  diurnalAsset: "data/lv-diurnal.json",
  heatSeasonAsset: "data/lv-heat-season.json",
  // heatDeathsAsset deferred: Clark County / Southern Nevada Health District do
  // publish heat-death data, but it hasn't yet been transcribed and verified to
  // the primary-source bar in analysis/HEAT_DEATHS.md. Omitting it leaves the
  // card hidden for Las Vegas until that verification is done (a clean follow-up).
  streaksAsset: "data/lv-streaks.json",
  gridAsset: "data/lv-grid.json",
  normalsAsset: "data/lv-normals.json",
  cddSplitAsset: "data/lv-cdd-split.json",
  // decennial census, Clark County, NV (US Census Bureau)
  metroPopulation: {
    1950: 48289, 1960: 127016, 1970: 273288, 1980: 463087,
    1990: 741459, 2000: 1375765, 2010: 1951269, 2020: 2265461,
  },
};

// The city registry the picker iterates. Phoenix is the flagship (first).

// Fourth city. El Paso has the cleanest control of the set: its open-desert pair
// (White Sands) sits at nearly the same elevation, so the city-vs-desert night
// gap is largely free of the elevation confound the other pairs carry.
export const ELPASO = {
  id: "ep",
  name: "El Paso, TX",
  shortName: "El Paso",
  threadSid: "ELPthr 9",
  recordStart: "1887-01-01",
  stationLabel:
    "El Paso Area ThreadEx record (early downtown record spliced to El Paso Intl, KELP)",
  urbanShort: "El Paso Intl",
  baseline: { start: 1970, end: 1979, label: "1970s" },
  windows: [
    { y: 1970, label: "Since 1970" },
    { y: 1948, label: "Since 1948" },
  ],
  latLon: [31.8111, -106.3758],
  rural: {
    sid: "USC00299686",
    name: "White Sands National Monument",
    short: "White Sands",
    firstYear: 1948,
    distance: "~70 miles north",
    elevationNote:
      "White Sands sits at nearly the same elevation as El Paso Intl (~90 ft difference), so unlike the other cities' pairs this gap is essentially free of the elevation confound — the cleanest control in the set.",
    growthCaveat:
      "White Sands is protected open desert (a national park unit), so the reference stays genuinely rural; the city-vs-desert gap is a like-for-like read.",
    robustnessNote:
      "The monument's COOP record has occasional gaps; the city-vs-desert gap and its growth are computed from the complete years and re-checked from ACIS in verify_v0.py.",
  },
  citations: [
    {
      label: "NOAA/NWS ACIS web services",
      url: "https://www.rcc-acis.org/docs_webservices.html",
      note: "The official station record this page queries live in your browser.",
    },
    {
      label: "NWS El Paso (Weather Forecast Office, EPZ) — local climate records",
      url: "https://www.weather.gov/epz/",
      note: "Local climate normals and records for the El Paso / Santa Teresa area.",
    },
    {
      label: "Climate Central, \"Warm Summer Nights\" (2025)",
      url: "https://www.climatecentral.org/climate-matters/warm-summer-nights-2025",
      note: "Summer nights across the Southwest have warmed ~4.5°F on average since 1970; El Paso's overnight lows are rising about +1.5°F/decade in the ACIS record.",
    },
  ],
  repoUrl: "https://github.com/poetac/phoenix_nights",
  diurnalAsset: "data/ep-diurnal.json",
  heatSeasonAsset: "data/ep-heat-season.json",
  // heatDeathsAsset deferred: not yet transcribed/verified to the HEAT_DEATHS.md
  // primary-source bar; the card cleanly omits until then.
  streaksAsset: "data/ep-streaks.json",
  gridAsset: "data/ep-grid.json",
  normalsAsset: "data/ep-normals.json",
  cddSplitAsset: "data/ep-cdd-split.json",
  // decennial census, El Paso County, TX (US Census Bureau)
  metroPopulation: {
    1950: 194968, 1960: 314070, 1970: 359291, 1980: 479899,
    1990: 591610, 2000: 679622, 2010: 800647, 2020: 865657,
  },
};

const YUMA = {
  id: "yum",
  name: "Yuma, AZ",
  shortName: "Yuma",
  threadSid: "YUMthr 9",
  recordStart: "1893-01-01",
  stationLabel:
    "Yuma Area ThreadEx record (Yuma MCAS / Yuma Intl)",
  urbanShort: "Yuma Intl",
  baseline: { start: 1970, end: 1979, label: "1970s" },
  windows: [
    { y: 1970, label: "Since 1970" },
    { y: 1948, label: "Since 1948" },
  ],
  latLon: [32.6927, -114.6277],
  rural: {
    sid: "USW00003125",
    name: "Yuma Proving Ground",
    short: "Yuma Proving Ground",
    firstYear: 1955,
    distance: "~19 miles NE",
    elevationNote:
      "Yuma Proving Ground sits within ~110 ft of the Yuma stations' elevation, so this gap is essentially free of the elevation confound — a clean low-desert control like El Paso's White Sands.",
    growthCaveat:
      "The Proving Ground is sparsely developed federal desert, so the reference stays genuinely rural; the city-vs-desert read is like-for-like.",
    robustnessNote:
      "The COOP record runs from 1955; the gap and its growth are computed from complete years and re-checked from ACIS in verify_v0.py.",
  },
  citations: [
    {
      label: "NOAA/NWS ACIS web services",
      url: "https://www.rcc-acis.org/docs_webservices.html",
      note: "The official station record this page queries live in your browser.",
    },
    {
      label: "NWS Phoenix (Weather Forecast Office, PSR) — serves Yuma County",
      url: "https://www.weather.gov/psr/",
      note: "Local climate normals and records for the Yuma area.",
    },
    {
      label: "Climate Central, \"Warm Summer Nights\" (2025)",
      url: "https://www.climatecentral.org/climate-matters/warm-summer-nights-2025",
      note: "Summer nights across the interior West have warmed sharply since 1970; Yuma's overnight lows are rising about +0.8°F/decade in the ACIS record.",
    },
  ],
  repoUrl: "https://github.com/poetac/phoenix_nights",
  heatSeasonAsset: "data/yum-heat-season.json",
  streaksAsset: "data/yum-streaks.json",
  normalsAsset: "data/yum-normals.json",
  cddSplitAsset: "data/yum-cdd-split.json",
  diurnalAsset: "data/yum-diurnal.json",
  // grid asset deferred: no clean single-utility metro balancing authority
  // for this city, so the grid card omits rather than show wrong-region demand.
};

const RENO = {
  id: "rno",
  name: "Reno, NV",
  shortName: "Reno",
  threadSid: "RNOthr 9",
  recordStart: "1893-01-01",
  stationLabel:
    "Reno Area ThreadEx record (downtown record spliced to Reno-Tahoe Intl, KRNO)",
  urbanShort: "Reno-Tahoe Intl",
  baseline: { start: 1970, end: 1979, label: "1970s" },
  windows: [
    { y: 1970, label: "Since 1970" },
    { y: 1948, label: "Since 1948" },
  ],
  latLon: [39.4985, -119.7681],
  rural: {
    sid: "USC00048758",
    name: "Tahoe City",
    short: "Tahoe City",
    firstYear: 1909,
    distance: "~34 miles SW",
    elevationNote:
      "Tahoe City sits ~1,800 ft ABOVE Reno, so much of the absolute night-low gap is elevation, not city heat — the honest signal here is the gap's GROWTH over time, not its size. Reno's mountain basin has no low-elevation long-record rural neighbor.",
    growthCaveat:
      "Tahoe City is a small lakeshore community that has grown over the record; if anything that warms the reference, so the city's excess night warming is understated rather than inflated.",
    robustnessNote:
      "Reno's +2.16°F/decade overnight-low trend is the fastest in the set and far outruns Tahoe City's +0.27; reproduce with analysis/city_audit.py.",
  },
  citations: [
    {
      label: "NOAA/NWS ACIS web services",
      url: "https://www.rcc-acis.org/docs_webservices.html",
      note: "The official station record this page queries live in your browser.",
    },
    {
      label: "NWS Reno (Weather Forecast Office, REV)",
      url: "https://www.weather.gov/rev/",
      note: "Local climate normals and records for the Reno area.",
    },
    {
      label: "Climate Central, \"Warm Summer Nights\" (2025)",
      url: "https://www.climatecentral.org/climate-matters/warm-summer-nights-2025",
      note: "Summer nights across the interior West have warmed sharply since 1970; Reno's overnight lows are rising about +2.2°F/decade in the ACIS record.",
    },
  ],
  repoUrl: "https://github.com/poetac/phoenix_nights",
  heatSeasonAsset: "data/rno-heat-season.json",
  streaksAsset: "data/rno-streaks.json",
  normalsAsset: "data/rno-normals.json",
  cddSplitAsset: "data/rno-cdd-split.json",
  diurnalAsset: "data/rno-diurnal.json",
  // grid asset deferred: no clean single-utility metro balancing authority
  // for this city, so the grid card omits rather than show wrong-region demand.
};

const ALBUQUERQUE = {
  id: "abq",
  name: "Albuquerque, NM",
  shortName: "Albuquerque",
  threadSid: "ABQthr 9",
  recordStart: "1893-01-01",
  stationLabel:
    "Albuquerque Area ThreadEx record (Albuquerque Intl Sunport, KABQ)",
  urbanShort: "Sunport",
  baseline: { start: 1970, end: 1979, label: "1970s" },
  windows: [
    { y: 1970, label: "Since 1970" },
    { y: 1948, label: "Since 1948" },
  ],
  latLon: [35.0844, -106.6504],
  rural: {
    sid: "USC00295150",
    name: "Los Lunas 3 SSW",
    short: "Los Lunas",
    firstYear: 1923,
    distance: "~25 miles S",
    elevationNote:
      "Los Lunas sits ~500 ft BELOW the Sunport, so the elevation confound runs the other way — the city is higher yet its nights warm faster, which strengthens rather than inflates the urban signal.",
    growthCaveat:
      "Los Lunas has suburbanized along the Rio Grande; a warming reference understates the city's excess, not the reverse.",
    robustnessNote:
      "Swapping in higher, slower Santa Fe widens the gap; this card uses the closer, lower Los Lunas as the more conservative control. Reproduce with analysis/city_audit.py.",
  },
  citations: [
    {
      label: "NOAA/NWS ACIS web services",
      url: "https://www.rcc-acis.org/docs_webservices.html",
      note: "The official station record this page queries live in your browser.",
    },
    {
      label: "NWS Albuquerque (Weather Forecast Office, ABQ)",
      url: "https://www.weather.gov/abq/",
      note: "Local climate normals and records for the Albuquerque area.",
    },
    {
      label: "Climate Central, \"Warm Summer Nights\" (2025)",
      url: "https://www.climatecentral.org/climate-matters/warm-summer-nights-2025",
      note: "Summer nights across the interior West have warmed sharply since 1970; Albuquerque's overnight lows are rising about +1.1°F/decade in the ACIS record.",
    },
  ],
  repoUrl: "https://github.com/poetac/phoenix_nights",
  heatSeasonAsset: "data/abq-heat-season.json",
  streaksAsset: "data/abq-streaks.json",
  normalsAsset: "data/abq-normals.json",
  cddSplitAsset: "data/abq-cdd-split.json",
  gridAsset: "data/abq-grid.json",
  diurnalAsset: "data/abq-diurnal.json",
  // grid card uses PNM, the Albuquerque metro's single balancing authority.
};

const SALTLAKE = {
  id: "slc",
  name: "Salt Lake City, UT",
  shortName: "Salt Lake City",
  threadSid: "SLCthr 9",
  recordStart: "1893-01-01",
  stationLabel:
    "Salt Lake City Area ThreadEx record (Salt Lake City Intl, KSLC)",
  urbanShort: "SLC Intl",
  baseline: { start: 1970, end: 1979, label: "1970s" },
  windows: [
    { y: 1970, label: "Since 1970" },
    { y: 1948, label: "Since 1948" },
  ],
  latLon: [40.7608, -111.8910],
  rural: {
    sid: "USC00429133",
    name: "Vernon",
    short: "Vernon",
    firstYear: 1953,
    distance: "~60 miles SW",
    elevationNote:
      "Vernon sits ~1,200 ft above Salt Lake City, so part of the absolute gap is elevation; the honest signal is the gap's growth, not its size. Vernon is the longest slow-warming rural record within the basin's reach.",
    growthCaveat:
      "Vernon is tiny high-desert ranchland with negligible development, so it stays a genuinely rural reference.",
    robustnessNote:
      "Salt Lake's +1.05°F/decade overnight-low trend outruns Vernon's +0.15; the gap and its growth are re-checked from ACIS in verify_v0.py.",
  },
  citations: [
    {
      label: "NOAA/NWS ACIS web services",
      url: "https://www.rcc-acis.org/docs_webservices.html",
      note: "The official station record this page queries live in your browser.",
    },
    {
      label: "NWS Salt Lake City (Weather Forecast Office, SLC)",
      url: "https://www.weather.gov/slc/",
      note: "Local climate normals and records for the Salt Lake City area.",
    },
    {
      label: "Climate Central, \"Warm Summer Nights\" (2025)",
      url: "https://www.climatecentral.org/climate-matters/warm-summer-nights-2025",
      note: "Summer nights across the interior West have warmed sharply since 1970; Salt Lake City's overnight lows are rising about +1.1°F/decade in the ACIS record.",
    },
  ],
  repoUrl: "https://github.com/poetac/phoenix_nights",
  heatSeasonAsset: "data/slc-heat-season.json",
  streaksAsset: "data/slc-streaks.json",
  normalsAsset: "data/slc-normals.json",
  cddSplitAsset: "data/slc-cdd-split.json",
  diurnalAsset: "data/slc-diurnal.json",
  // grid asset deferred: no clean single-utility metro balancing authority
  // for this city, so the grid card omits rather than show wrong-region demand.
};

const BOISE = {
  id: "boi",
  name: "Boise, ID",
  shortName: "Boise",
  threadSid: "BOIthr 9",
  recordStart: "1893-01-01",
  stationLabel:
    "Boise Area ThreadEx record (Boise Air Terminal, KBOI)",
  urbanShort: "Boise Air Terminal",
  baseline: { start: 1970, end: 1979, label: "1970s" },
  windows: [
    { y: 1970, label: "Since 1970" },
    { y: 1948, label: "Since 1948" },
  ],
  latLon: [43.6150, -116.2023],
  rural: {
    sid: "USC00102942",
    name: "Emmett 2 E",
    short: "Emmett",
    firstYear: 1906,
    distance: "~25 miles NW",
    elevationNote:
      "Emmett sits ~300 ft below Boise, so the elevation confound is small and runs toward the city being cooler at baseline — the city's faster night warming is not an elevation artifact.",
    growthCaveat:
      "Emmett is a small agricultural town; any modest growth there would understate the city's excess warming.",
    robustnessNote:
      "Boise's +0.94°F/decade overnight-low trend outruns Emmett's +0.33; reproduce with analysis/city_audit.py.",
  },
  citations: [
    {
      label: "NOAA/NWS ACIS web services",
      url: "https://www.rcc-acis.org/docs_webservices.html",
      note: "The official station record this page queries live in your browser.",
    },
    {
      label: "NWS Boise (Weather Forecast Office, BOI)",
      url: "https://www.weather.gov/boi/",
      note: "Local climate normals and records for the Boise area.",
    },
    {
      label: "Climate Central, \"Warm Summer Nights\" (2025)",
      url: "https://www.climatecentral.org/climate-matters/warm-summer-nights-2025",
      note: "Summer nights across the interior West have warmed sharply since 1970; Boise's overnight lows are rising about +0.9°F/decade in the ACIS record.",
    },
  ],
  repoUrl: "https://github.com/poetac/phoenix_nights",
  heatSeasonAsset: "data/boi-heat-season.json",
  streaksAsset: "data/boi-streaks.json",
  normalsAsset: "data/boi-normals.json",
  cddSplitAsset: "data/boi-cdd-split.json",
  gridAsset: "data/boi-grid.json",
  diurnalAsset: "data/boi-diurnal.json",
  // grid card uses IPCO (Idaho Power), the Boise metro's balancing authority.
};

export const CITIES = [PHOENIX, TUCSON, LASVEGAS, ELPASO, YUMA, RENO, ALBUQUERQUE, SALTLAKE, BOISE];
