// AUTO-GENERATED by apps/web/scripts/build-world-map.mjs — do not edit by hand.
// Pre-projected world land outlines (d3 geoNaturalEarth1, world-atlas countries-110m)
// + each City Signals city's projected [x, y]. Generated by the "Build world map"
// GitHub Action (it installs d3-geo/world-atlas, which need a network install).
// Until that runs, this stub is null and CityMap falls back to the US Albers map, so
// the app always builds and renders.
export const WORLD_MAP = null;
